### ISSUE TITLE
Segmentation fault in examples

### ISSUE THREAD

**Issue by n-s-kiselev** [libglui/glui#88]
I use release **2.37** (and **2.36**) on Ubuntu **14.04** (on two different mashines result is identical).
Compilation went normally (only few warnings), but when I try to run examples I got:
`Segmentation fault (core dumped)`
In MacOS the same release gives no error and all examples work properly.
What could be a reason for this issue?
Thank you in advance!

**Comment by nigels-com** [comment]
You might have more luck with the current master branch from github.
I have 16.04 here I can test with, what is your GPU/driver?

- Nigel

**Comment by nigels-com** [comment]
I just merged to master a fix for some compilation warnings I see for gcc 5.5.0 on Xenial.

**Comment by n-s-kiselev** [comment]
I have checked it!
Those warnings which were before indeed dissipated, but some small warnings left.
I suppose it, ok.
But examples still do not work, see below: 

kiselev@U14:~/Git/glui$ git pull
remote: Counting objects: 8, done.
remote: Total 8 (delta 5), reused 5 (delta 5), pack-reused 3
Unpacking objects: 100% (8/8), done.
From https://github.com/libglui/glui
   ad0f3a8..1e3efbe  master     -> origin/master
Updating ad0f3a8..1e3efbe
Fast-forward
 glui_list.cpp      | 3 ++-
 glui_textbox.cpp   | 2 +-
 glui_treepanel.cpp | 6 +++---
 include/GL/glui.h  | 2 +-
 4 files changed, 7 insertions(+), 6 deletions(-)
kiselev@U14:~/Git/glui$ make clean
rm -f *.o lib/libglui.a bin/example1 bin/example2 bin/example3 bin/example4 bin/example5 bin/example6 bin/ppm2array 
rm -fr doc/doxygen
kiselev@U14:~/Git/glui$ make 
......
glui_commandline.cpp: In member function ‘void GLUI_CommandLine::dump(FILE*, const GLUI_String&)’:
glui_commandline.cpp:195:23: warning: format ‘%p’ expects argument of type ‘void*’, but argument 4 has type ‘GLUI_CommandLine*’ [-Wformat=]
     (int)text.length());
                       ^
......
kiselev@U14:~/Git/glui$ cd bin/
kiselev@U14:~/Git/glui/bin$ ./example1
Segmentation fault (core dumped)
kiselev@U14:~/Git/glui/bin$ gdb --args ./example1
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./example1...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/kiselev/Git/glui/bin/example1 

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()

**Comment by nigels-com** [comment]
I checked just now with Ubuntu 18.04 (Bionic), seems fine.

Is there anyone using Ubuntu 14.04 (Trusty) that can confirm this problem?

**Comment by nigels-com** [comment]
valgrind seems clean for Ubuntu 18.04.

[valgrind.example.txt](https://github.com/libglui/glui/files/3268006/valgrind.example.txt)
